/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/answers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Answer
     * @description Answer from the live Postgres index and record it for audit.
     */
    post: operations["create_answer_api_v1_answers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/answers/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stream Answer
     * @description The same answer as server-sent events: `stage` as each stage starts, then
     *     `answer` once it is verified, or `error`. Unverified text is never sent.
     */
    post: operations["stream_answer_api_v1_answers_stream_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Liveness: the process answers HTTP. It checks nothing else, so a slow model
     *     or database never gets a working process restarted.
     */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readyz
     * @description Readiness: whether an answer can be served now. HTTP 503 until the database
     *     has a matching live index and every model server has loaded its model.
     */
    get: operations["readyz_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AnswerRequest
     * @description A question for the v1 API, checked after surrounding spaces are removed, and
     *     the conversation it continues, if any. Any other field is refused.
     */
    AnswerRequest: {
      /** Question */
      question: string;
      /** Conversation Id */
      conversation_id?: string | null;
    };
    /** AnswerView */
    AnswerView: {
      /** Question */
      question: string;
      /** Status */
      status: string;
      /** Notice */
      notice: string;
      /** Claims */
      claims: components["schemas"]["ClaimView"][];
      /** Sources */
      sources: components["schemas"]["Source"][];
      /** Closest Pages */
      closest_pages: components["schemas"]["Page"][];
    };
    /** ClaimView */
    ClaimView: {
      /** Text */
      text: string;
      /** Sources */
      sources: number[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Page */
    Page: {
      /** Title */
      title: string;
      /** Url */
      url: string;
    };
    /** Readiness */
    Readiness: {
      /** Ready */
      ready: boolean;
      /** Checks */
      checks: {
        [key: string]: boolean;
      };
    };
    /** RecordedAnswer */
    RecordedAnswer: {
      /** Id */
      id: number;
      /** Conversation Id */
      conversation_id: string;
      /** Turn */
      turn: number;
      /** Understood As */
      understood_as: string[];
      answer: components["schemas"]["AnswerView"];
    };
    /**
     * Source
     * @description One verified quote, numbered so claims can point to it.
     */
    Source: {
      /** Number */
      number: number;
      /** Title */
      title: string;
      /** Heading */
      heading: string;
      /** Quote */
      quote: string;
      /** Link */
      link: string;
      /** Url */
      url: string;
      /** Captured */
      captured: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create_answer_api_v1_answers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnswerRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecordedAnswer"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_answer_api_v1_answers_stream_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnswerRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
    };
  };
}
